<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>En_Content_Layout_Application_Layer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mappers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\En-Content-Layout-Domain-Layer\En-Content-Layout-Domain-Layer.csproj" />
  </ItemGroup>

</Project>
